version: '2'
services:
  templogger:
    build: .
    depends_on:
      - graphite

  graphite:
    image: sitespeedio/graphite:0.9.14
    volumes:
      - "/opt/graphite/passwd:/etc/nginx/.htpasswd"
      - "/opt/graphite/passwd:/opt/graphite/storage/whisper"
    ports:
      - "8080:80"
