version: '2'
services:
  templogger:
    build: .
    depends_on:
      - graphite
    env_file:
      - "${SECRETS}"


  graphite:
    image: sitespeedio/graphite:0.9.14
    ports:
      - "8080:80"
